{% set name = "jsongrapher" %}
{% set version = "2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jsongrapher-{{ version }}.tar.gz
  sha256: aaf0618ae8faf48456dda5b9425b93b31de91f270c81f0808e0397653c79a5ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy

test:
  imports:
    - JSONGrapher
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AdityaSavara/jsongrapher-py
  summary: The python version of JSONGrapher with tools for creating JSONGrapher Records.
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AdityaSavara
